services:
  istoreos:
    # 使用你自己的 ARM64 定制镜像
    # 本地镜像示例：istoreos-fn:minimal-v1
    # 仓库镜像示例：yourname/istoreos-fn:minimal-v1
    image: <改成你的定制镜像地址>
    container_name: istoreos
    privileged: true
    restart: always
    command: /sbin/init
    environment:
      TZ: Asia/Shanghai
    volumes:
      - <改成宿主机目录>/root:/root
      - <改成宿主机目录>/etc:/etc
      - <改成宿主机目录>/overlay:/overlay
    networks:
      ios_macnet:
        ipv4_address: <改成容器固定IP>

networks:
  ios_macnet:
    name: ios_macnet
    driver: macvlan
    driver_opts:
      # 可用 ip link show 查看宿主机网卡名
      parent: <改成宿主机网卡名>
    ipam:
      config:
        - subnet: <改成局域网网段，例如 192.168.66.0/24>
          gateway: <改成局域网网关，例如 192.168.66.1>
